### ISSUE TITLE
Search Bar Doesn't Work

### ISSUE THREAD

**Issue by pandaxtc** [Pitu/Magane#3]
Title. The search bar, when clicked on, immediately defocuses, and the cursor returns to the message box. 

It is possible to put text in the search bar if I click and hold on it while typing, but when I press enter, the Discord client reloads, and sending stickers doesn't work afterwards until I quit + relaunch Discord.

**Comment by Pitu** [comment]
Yeah this is a known issue and something that will be fixed on the upcoming version. At the moment search bar doesn't work at all, and it's intended that way because there was nothing to search for since sticker packs don't have metadata. Now they do, and update should be rolling out next week most likely.

**Comment by dragxtcon** [comment]
Oh, cool. Thanks, looking forward to it!

**Comment by BobbyWibowo** [comment]
@Pitu Any plan to implement this on master anytime soon? I actually already added search bar to my fork quite a while ago, though I completely forgot this issue existed. I think I can make a PR soon:tm: :wink:

**Comment by Pitu** [comment]
This is already implemented in 1c3fef3 thanks to @BobbyWibowo . Restarting Discord should be enough to get the latest version.
