### ISSUE TITLE
Question of whether shortcut keys and such can be implemented, or if they already are.

### ISSUE THREAD

**Issue by KRKMZERO** [Pitu/Magane#61]
Hey, I like and use this plugin.
But I also have a problem with the sticker button disappearing when I use it with certain other plugins!

If there was a shortcut key I could send them without worrying...

If you haven't implemented it, I don't blame you.
When I use it, I go out of my way to remove the other plugins.

I'm not really looking for a response.
If you don't mind, you can remove it.

If you have a suggestion, it would be better if you could add this plugin to the "GIF", "Stamp", and "Emoji" tabs, and if you have a suggestion, you can add the "GIF" tab to the "Stamp" tab.

I would also be happy to see a shortcut key for this plugin.

Thank you for reading!

**Comment by BobbyWibowo** [comment]
> But I also have a problem with the sticker button disappearing when I use it with certain other plugins!

It's known that it's incompatible with certain plugins
Due to technical limitations involving the way Magane was written, it cannot be fixed for the time being

You can use the solution described in https://github.com/Pitu/Magane/issues/47#issuecomment-964469495 as a temporary workaround
However, it will only patch Magane disappearing during Discord first launch
Magane will still break if the conflicting plugins are manually (re)loaded after launch

There are plans to rewrite Magane from scratch, which should also fix the conflicting issues altogether, however that's something for the ~~distant~~ future

> If there was a shortcut key I could send them without worrying...

Unfortunately, even if shortcut key was implemented, the way Magane breaks with those plugins, will cause the shortcut key to cease functioning when it happens anyways

> If you have a suggestion, it would be better if you could add this plugin to the "GIF", "Stamp", and "Emoji" tabs, and if you have a suggestion, you can add the "GIF" tab to the "Stamp" tab.

This is _unlikely_ to be implemented even on the rewrite, whenever that happens
A good portion of us prefer Magane having a bigger window than Discord's emojis window, just like the current implementation
