### ISSUE TITLE
[Suggestion] Line Sticker Button Location

### ISSUE THREAD

**Issue by reynoldyehezkiel** [Pitu/Magane#65]
I have suggestion about button location

Instead here
![Screenshot (125)](https://user-images.githubusercontent.com/73789263/176636398-cb9b2cb2-24f0-4e33-ad09-713c45061b18.png)

Better here
![Screenshot (126)](https://user-images.githubusercontent.com/73789263/176636284-5d8b633e-7d83-419c-a8ca-fbfb49760803.png)

**Comment by BobbyWibowo** [comment]
It currently is intentionally kept that way for simplicity with current implementation

If the BD rewrite gets forwarded, that will change, otherwise the current method will be kept

And yes am aware of various quirks the current implementation causes (such as texts from the input can actually clip under the button, update delay, etc), but yeah, it is what it is

**Comment by reynoldyehezkiel** [comment]
Ok, thanks for the explanation

**Comment by BobbyWibowo** [comment]
Ah, I forgot to mention but it'll be implemented with the PR linked above
Had a stroke of inspiration, lmao
