### ISSUE TITLE
failed to upload images when using Forum Channel in split view

### ISSUE THREAD

**Issue by w-e-w** [Pitu/Magane#82]
in Forum Channel in split view the plugin is unable to upload the sticker to the forum channel

I believe what happens is that, when in split view Magane tries send the sticker to the Forum panel on the left and tries to create a "New Post"
as opposed to sending the sticker to chat on the right
![image](https://user-images.githubusercontent.com/40751091/212226346-9a4bd27b-bd7c-49e1-bff9-24ee62c6209f.png)
![dc forum channel](https://user-images.githubusercontent.com/40751091/211735943-b0700148-9f30-4eca-bf61-9b0609f88c06.png)

version 3.2.9

**Comment by BobbyWibowo** [comment]
Sorry for the late respond, usually busier on holiday season

For the time being, you can choose to open the thread in a full view as shown in the screenshot below:
![screenshot](https://i.fiery.me/ferr.png)

The code used currently does not have context about opened threads

The forum itself is an actual channel, so the code is fetching its ID, instead of the opened thread's
And since you obviously cannot send anything to the forum itself, instead of the threads within it, you'll end up seeing failed upload notice

An update will come eventually that makes you not have to do this at all

**Comment by w-e-w** [comment]
Thank for your response

I merely a bring awareness to the issue
I'm aware that I can open the threads into fullview to make it work

you explanation is good and not just repeating
as I don't have any understanding of the code base, I only deduce the behavior from observation
it is good to know that my observation and hypothesis is correct
